:toc:
:toclevels: 1
:toc-placement!:

= Dragons Dogma Online - Server

image::https://github.com/mrnamwen/Arrowgene.DragonsDogmaOnline/actions/workflows/build.yaml/badge.svg[]

Server Emulator for the Game Dragons Dogma Online.

'''

toc::[]

'''

== AI Disclosure
This is a personal fork of @sebastian-heinz's (https://github.com/sebastian-heinz) amazing work on emulating the Dragon's Dogma Online server. This repo contains a variety of bleeding-edge improvement, balance changes, and custom code to achieve feature parity with retail and rebalance the game for solo or low-population player counts. There are several features here that, as far as I am aware, no other server have implemented.

However, this was only possible thanks to **heavy use of AI**, namely in decoding the packet structures, analyzing the raw IDA dumps, and helping to trial-and-error a lot of the lower level functions. As a result, the code within is potentially unordered, badly scales, and under certain edge cases (and even non-edge cases) may disconnect you or crash the game.

I am extensively working on improving the feature set, fixing bugs, and improving stability, but please understand that **there are no guarantees regarding the quality of my changes**. Additionally, due to the way I have approached development (namely deciding to not git track anything until I actually implemented half the features below), I cannot safely merge this into the main project and will not issue any PRs to implement these changes - they would need to be decoupled and reconstructed into something that isn't a +7000/-900 diff.

== Disclaimer
The project is intended for educational purpose only.

== Fork Improvements

This fork includes significant enhancements over the upstream repository, including new game systems (Gacha, GP Shop, Pawn Expeditions, Mandragora Crafting, Reward Missions, Large Delivery Events), database migrations, and configurable JSON assets.

For the complete list of features, see xref:./docs/FEATURES.adoc[Fork Features & Improvements].

== Developer Setup

. Clone the repository
.. `git clone https://github.com/mrnamwen/Arrowgene.DragonsDogmaOnline.git`
. Install .NET 10.0 SDK or later https://dotnet.microsoft.com/download
. Use your IDE of choice
.. *Visual Studio*
... Open the `DragonsDogmaOnline.sln`-file
... Note: Minimum version of "Visual Studio 2022" or later.
.. *VS Code*
... Download IDE: https://code.visualstudio.com/download  
... C# Plugin: https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp  
... Open the Project Folder: `\Arrowgene.DragonsDogmaOnline`
.. *IntelliJ Rider*
... https://www.jetbrains.com/rider/
... Note: Minimum version of "IntelliJ Rider 2021.3" or later.
... Open the `DragonsDogmaOnline.sln`-file
. Debug the Project
.. Run the `Ddon.Cli`-Project with arguments `server start`

== User Setup
. Clone the repository
.. `git clone https://github.com/mrnamwen/Arrowgene.DragonsDogmaOnline.git`
. Install .NET 10.0 SDK or later https://dotnet.microsoft.com/download
. Run `publish.cmd` or `publish.sh` to build the server files.
. If updating from a previous build of the server...
.. Make sure that your database file `db.sqlite` is in the proper location, usually `Arrowgene.DragonsDogmaOnline\publish\win-x64-#.#.#.#\Server\Files\Database`.
.. You may have to migrate your database schema by running `MigrateDatabase.cmd`, which can be found in `Arrowgene.DragonsDogmaOnline\publish\win-x64-#.#.#.#`.
. Launch the server with `StartServer.cmd`, which can be found in `Arrowgene.DragonsDogmaOnline\publish\win-x64-#.#.#.#`.
. For frequently asked questions, see https://github.com/mrnamwen/Arrowgene.DragonsDogmaOnline/blob/develop/docs/faq.md

== Deployment

The application (server) requires the (ASP).NET runtime 10 to function. Alternatively the SDK also works and is required when building from source.

On a high level, a total of four components are required to successfully connect a client:

. Web server
. Login server
. Game server
. Database

All of these components are provided & automatically started up in the default developer setup outlined above.

=== Persistence 

There is support for SQLite via System.Data.SQLite (behaves slightly differently from Microsoft.Data.Sqlite!) as a file-based setup or an in-memory setup with built-in backups upon starting and closing (i.e. all progress is lost if the application crashes!).
This is mostly suitable for development as SQLite does not scale well for multiple parallel write/transaction operations.

For a more scalable setup there is also support for Postgres via Npgsql.

For both databases there are sample configurations, schemas and containerization setups.

=== Container setup

It is also possible to run a containerized setup.
A xref:./Dockerfile[Dockerfile] is provided which encapsulates everything required to build & publish the server from source. Three separate docker-compose files are provided depending on the desired database. None of these actually reference any image and instead rely on ad-hoc source code builds as the image is currently not publicly available.

. xref:./docker-compose.yml[SQLite-enabled docker-compose]
.. `docker-compose up`
. xref:./docker-compose.psql.yml[PostgreSQL-enabled docker-compose]
.. `docker-compose -f docker-compose.psql.yml up`

==== Useful run commands

* Force rebuild `docker-compose up --build`
* Clean up & delete persistent volumes (data) as well `docker-compose down -v`
* Only build the image `docker-compose build`
* Build for other runtimes, e.g. arm64 `RUNTIME=linux-arm64 docker-compose build`
* All-in-one clean & rebuild `docker-compose down -v && docker-compose up --build`
* All-in-one clean & rebuild & arm64 `RUNTIME=linux-arm64 docker-compose down -v && docker-compose up --build`

== Server
With default configuration the server will listen on following ports:

[source]
----
52099 - http/download
52000 - tcp/gameserver
52100 - tcp/loginserver
----

ensure that no other local services listen on these ports.

== Client
Launch the client with the following args:

`"DDO.exe" "addr=localhost port=52100 token=00000000000000000000 DL=http://127.0.0.1:52099/win/ LVer=03.04.003.20181115.0 RVer=3040008"`

== Progress
See xref:./docs/WHAT_WORKS.md[What Works?] for detailed feature implementation status.

== Guidelines
=== Git 
==== Workflow
The work on this project should happen via `feature-branches`
   
Feature branches (or sometimes called topic branches) are used to develop new features for the upcoming or a distant future release. 
When starting development of a feature, the target release in which this feature will be incorporated may well be unknown at that point. 
The essence of a feature branch is that it exists as long as the feature is in development, 
but will eventually be merged back into develop (to definitely add the new feature to the upcoming release) or discarded (in case of a disappointing experiment).

1. Create a new `feature/feature-name` or `fix/bug-fix-name` branch from master
2. Push all your changes to that branch
3. Create a Pull Request to merge that branch into `master`

=== Best Practise
- Do not use Console.WriteLine etc., use the specially designed logger.
- Own the Code: extract solutions, discard libraries.
- Annotate functions with documentation comments (https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/documentation-comments).

=== C# Coding Standards and Naming Conventions

[options="header"]
|=========================================================
| Object Name      | Notation   | Char Mask  | Underscores
| Class name       | PascalCase | [A-z][0-9] | No
| Constructor name | PascalCase | [A-z][0-9] | No
| Method name      | PascalCase | [A-z][0-9] | No
| Method arguments | camelCase  | [A-z][0-9] | No
| Local variables  | camelCase  | [A-z][0-9] | No
| Constants name   | PascalCase | [A-z][0-9] | No
| Field name       | _camelCase | [A-z][0-9] | Yes
| Properties name  | PascalCase | [A-z][0-9] | No
| Delegate name    | PascalCase | [A-z]      | No
| Enum type name   | PascalCase | [A-z]      | No
|=========================================================

== Attribution
=== Contributors / Making It Happening
Let me preface with that this work could not exist without the excellent work of various individuals
- Ando - Reverse Engineering & Tooling (Session Splitter, Camellia Key Cracker)
- David - Reverse Engineering (unpacking PC Executable, defeating Anti Debug and CRC checks)
- The White Dragon Temple
- Nothilvien [@sebastian-heinz](https://github.com/sebastian-heinz) - Reverse Engineering & Server Code
  
(if you have been forgotten please reach out)

=== 3rd Parties and Libraries
- System.Data.SQLite (https://system.data.sqlite.org/)
- KaitaiStruct.Runtime.Csharp (https://kaitai.io/)
- Arrowgene.Networking (https://github.com/sebastian-heinz/Arrowgene.Networking)
- .NET Standard (https://github.com/dotnet/standard)
